server:
  port: 8080

spring:
  application:
    name: cloud-grpc-client-nacos
  sleuth:
    sampler:
      probability: 1
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

grpc:
  client:
    cloud-grpc-server-nacos:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
