server:
  port: 8082
spring:
  application:
    name: cloud-grpc-client-consul
  cloud:
    consul:
      discovery:
        registry: false
        port: 8500
        hostname: 127.0.0.1
grpc:
  client:
    cloud-grpc-server-consul:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
