server:
  port: 8080
spring:
  application:
    name: security-grpc-client
# auth.username: guest
auth.username: user
# auth.username: unknown
grpc:
  client:
    security-grpc-server:
      host:
        - 127.0.0.1
      port:
        - 9090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext